use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AyuPalette {
    pub bg: String,
    pub fg: String,
    pub surface: String,
    pub selection: String,
    pub comment: String,
    pub gutter: String,
    pub red: String,
    pub green: String,
    pub yellow: String,
    pub blue: String,
    pub purple: String,
    pub cyan: String,
    pub orange: String,
    pub br_red: String,
    pub br_green: String,
    pub br_blue: String,
    pub br_purple: String,
    pub br_cyan: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NamedPalette {
    pub name: String,
    pub palette: AyuPalette,
}

impl Default for AyuPalette {
    fn default() -> Self {
        Self {
            bg: "#0b0e14".into(),
            fg: "#bfbdb6".into(),
            surface: "#1e232b".into(),
            selection: "#1b3a5b".into(),
            comment: "#8b949e".into(),
            gutter: "#636a72".into(),
            red: "#ea6c73".into(),
            green: "#7fd962".into(),
            yellow: "#f9af4f".into(),
            blue: "#53bdfa".into(),
            purple: "#cda1fa".into(),
            cyan: "#90e1c6".into(),
            orange: "#ffb454".into(),
            br_red: "#f07178".into(),
            br_green: "#aad94c".into(),
            br_blue: "#59c2ff".into(),
            br_purple: "#d2a6ff".into(),
            br_cyan: "#95e6cb".into(),
        }
    }
}

pub fn builtin_palettes() -> Vec<NamedPalette> {
    vec![
        NamedPalette {
            name: "Ayu Dark".into(),
            palette: AyuPalette::default(),
        },
        NamedPalette {
            name: "Ayu Mirage".into(),
            palette: AyuPalette {
                bg: "#1f2430".into(),
                fg: "#cbccc6".into(),
                surface: "#272d38".into(),
                selection: "#33415e".into(),
                comment: "#5c6773".into(),
                gutter: "#707a8c".into(),
                red: "#f28779".into(),
                green: "#bae67e".into(),
                yellow: "#ffd580".into(),
                blue: "#73d0ff".into(),
                purple: "#d4bfff".into(),
                cyan: "#95e6cb".into(),
                orange: "#ffcc66".into(),
                br_red: "#ff6666".into(),
                br_green: "#a6cc70".into(),
                br_blue: "#5ccfe6".into(),
                br_purple: "#c3a6ff".into(),
                br_cyan: "#88d4ab".into(),
            },
        },
        NamedPalette {
            name: "Tokyo Night".into(),
            palette: AyuPalette {
                bg: "#1a1b26".into(),
                fg: "#c0caf5".into(),
                surface: "#24283b".into(),
                selection: "#283457".into(),
                comment: "#565f89".into(),
                gutter: "#3b4261".into(),
                red: "#f7768e".into(),
                green: "#9ece6a".into(),
                yellow: "#e0af68".into(),
                blue: "#7aa2f7".into(),
                purple: "#bb9af7".into(),
                cyan: "#7dcfff".into(),
                orange: "#ff9e64".into(),
                br_red: "#ff7a93".into(),
                br_green: "#b9f27c".into(),
                br_blue: "#7da6ff".into(),
                br_purple: "#c0a6ff".into(),
                br_cyan: "#0db9d7".into(),
            },
        },
        NamedPalette {
            name: "Catppuccin Mocha".into(),
            palette: AyuPalette {
                bg: "#1e1e2e".into(),
                fg: "#cdd6f4".into(),
                surface: "#313244".into(),
                selection: "#45475a".into(),
                comment: "#6c7086".into(),
                gutter: "#585b70".into(),
                red: "#f38ba8".into(),
                green: "#a6e3a1".into(),
                yellow: "#f9e2af".into(),
                blue: "#89b4fa".into(),
                purple: "#cba6f7".into(),
                cyan: "#94e2d5".into(),
                orange: "#fab387".into(),
                br_red: "#f38ba8".into(),
                br_green: "#a6e3a1".into(),
                br_blue: "#89dceb".into(),
                br_purple: "#f5c2e7".into(),
                br_cyan: "#94e2d5".into(),
            },
        },
        NamedPalette {
            name: "Dracula".into(),
            palette: AyuPalette {
                bg: "#282a36".into(),
                fg: "#f8f8f2".into(),
                surface: "#44475a".into(),
                selection: "#44475a".into(),
                comment: "#6272a4".into(),
                gutter: "#6272a4".into(),
                red: "#ff5555".into(),
                green: "#50fa7b".into(),
                yellow: "#f1fa8c".into(),
                blue: "#6272a4".into(),
                purple: "#bd93f9".into(),
                cyan: "#8be9fd".into(),
                orange: "#ffb86c".into(),
                br_red: "#ff6e6e".into(),
                br_green: "#69ff94".into(),
                br_blue: "#d6acff".into(),
                br_purple: "#ff92df".into(),
                br_cyan: "#a4ffff".into(),
            },
        },
        NamedPalette {
            name: "Nord".into(),
            palette: AyuPalette {
                bg: "#2e3440".into(),
                fg: "#d8dee9".into(),
                surface: "#3b4252".into(),
                selection: "#434c5e".into(),
                comment: "#4c566a".into(),
                gutter: "#4c566a".into(),
                red: "#bf616a".into(),
                green: "#a3be8c".into(),
                yellow: "#ebcb8b".into(),
                blue: "#5e81ac".into(),
                purple: "#b48ead".into(),
                cyan: "#88c0d0".into(),
                orange: "#d08770".into(),
                br_red: "#bf616a".into(),
                br_green: "#a3be8c".into(),
                br_blue: "#81a1c1".into(),
                br_purple: "#b48ead".into(),
                br_cyan: "#8fbcbb".into(),
            },
        },
        NamedPalette {
            name: "Gruvbox Dark".into(),
            palette: AyuPalette {
                bg: "#282828".into(),
                fg: "#ebdbb2".into(),
                surface: "#3c3836".into(),
                selection: "#504945".into(),
                comment: "#928374".into(),
                gutter: "#665c54".into(),
                red: "#cc241d".into(),
                green: "#98971a".into(),
                yellow: "#d79921".into(),
                blue: "#458588".into(),
                purple: "#b16286".into(),
                cyan: "#689d6a".into(),
                orange: "#d65d0e".into(),
                br_red: "#fb4934".into(),
                br_green: "#b8bb26".into(),
                br_blue: "#83a598".into(),
                br_purple: "#d3869b".into(),
                br_cyan: "#8ec07c".into(),
            },
        },
        NamedPalette {
            name: "One Dark".into(),
            palette: AyuPalette {
                bg: "#282c34".into(),
                fg: "#abb2bf".into(),
                surface: "#3e4451".into(),
                selection: "#3e4451".into(),
                comment: "#5c6370".into(),
                gutter: "#4b5263".into(),
                red: "#e06c75".into(),
                green: "#98c379".into(),
                yellow: "#e5c07b".into(),
                blue: "#61afef".into(),
                purple: "#c678dd".into(),
                cyan: "#56b6c2".into(),
                orange: "#d19a66".into(),
                br_red: "#be5046".into(),
                br_green: "#98c379".into(),
                br_blue: "#61afef".into(),
                br_purple: "#c678dd".into(),
                br_cyan: "#56b6c2".into(),
            },
        },
    ]
}
